os: linux
arch: ppc64le
sudo: required
language: shell

install:
  - sudo apt update
  - sudo apt-get install build-essential openjdk-8-jdk python zip unzip
  - github_version=0.29.1
  ##- sudo apt install build-essential python zip unzip gcc
  ##- sudo apt install default-jre default-jdk
  #- sudo apt install rpm

script:
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/bazel/ubuntu_14.04/bazel_bin_ppc64le_0.27.2
  - sudo mv bazel_bin_ppc64le_0.27.2 /usr/local/bin/bazel
  - sudo chmod +x /usr/local/bin/bazel
  - wget -q https://github.com/bazelbuild/bazel/releases/download/$github_version/bazel-$github_version-dist.zip
  - unzip -q bazel-$github_version-dist.zip -d bazel
  - git clone https://github.com/Unicamp-OpenPower/patch-apply
  - ./patch-apply/apply_patch.py bazel patchs
  - cd bazel
  - sudo EXTRA_BAZEL_ARGS=--host_javabase=@local_jdk//:jdk ./compile.sh
  - sudo mv output/bazel output/bazel_bin_ppc64le_$github_version
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/bazel/ubuntu_14.04 output/bazel_bin_ppc64le_$github_version"
